---
name: Update

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: checkout iterm2-website repository
        run: git clone --depth 1 https://github.com/gnachman/iTerm2-shell-integration.git

      - name: update utils checksums
        run: ./_utils/update_checksums.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
